apiVersion: v1
kind: Service
metadata:
  name: transaction-service
  namespace: banking
  labels:
    app: transaction-service
    app.kubernetes.io/part-of: banking-application
spec:
  selector:
    app: transaction-service
  ports:
  - name: http
    port: 8084
    targetPort: 8084
  type: ClusterIP
