apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: banking
  labels:
    app: api-gateway
    app.kubernetes.io/part-of: banking-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: '8080'
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: localhost:5001/banking/api-gateway:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          initialDelaySeconds: 120
          periodSeconds: 10
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          initialDelaySeconds: 180
          periodSeconds: 15
          failureThreshold: 5
        env:
        - name: JAVA_TOOL_OPTIONS
          value: -Xms256m -Xmx512m
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: banking-config
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        - name: EUREKA_INSTANCE_PREFERIPADDRESS
          valueFrom:
            configMapKeyRef:
              name: banking-config
              key: EUREKA_INSTANCE_PREFERIPADDRESS
        - name: APP_CONFIG_KEYCLOAK_INTERNAL_URL
          valueFrom:
            configMapKeyRef:
              name: banking-config
              key: APP_CONFIG_KEYCLOAK_INTERNAL_URL
        - name: APP_CONFIG_KEYCLOAK_EXTERNAL_URL
          valueFrom:
            configMapKeyRef:
              name: banking-config
              key: APP_CONFIG_KEYCLOAK_EXTERNAL_URL
        - name: MANAGEMENT_METRICS_DISTRIBUTION_PERCENTILESHISTOGRAM_HTTP_SERVER_REQUESTS
          value: 'true'
        - name: OTEL_TRACES_EXPORTER
          value: zipkin
        - name: OTEL_EXPORTER_ZIPKIN_ENDPOINT
          value: http://jaeger-collector.monitoring.svc.cluster.local:9411/api/v2/spans
        - name: OTEL_SERVICE_NAME
          value: api-gateway
        - name: OTEL_METRICS_EXPORTER
          value: none
        - name: OTEL_LOGS_EXPORTER
          value: none
        - name: OTEL_PROPAGATORS
          value: b3multi,tracecontext
      terminationGracePeriodSeconds: 30
