apiVersion: apps/v1
kind: Deployment
metadata:
  name: sequence-generator
  namespace: banking
  labels:
    app: sequence-generator
    app.kubernetes.io/part-of: banking-application
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sequence-generator
  template:
    metadata:
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /actuator/prometheus
        prometheus.io/port: '8083'
      labels:
        app: sequence-generator
    spec:
      containers:
      - name: sequence-generator
        image: localhost:5001/banking/sequence-generator:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8083
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /actuator/health/readiness
            port: http
          initialDelaySeconds: 120
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /actuator/health/liveness
            port: http
          initialDelaySeconds: 180
          periodSeconds: 15
        env:
        - name: JAVA_TOOL_OPTIONS
          value: -Xms128m -Xmx256m
        - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
          valueFrom:
            configMapKeyRef:
              name: banking-config
              key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        - name: EUREKA_INSTANCE_PREFERIPADDRESS
          valueFrom:
            configMapKeyRef:
              name: banking-config
              key: EUREKA_INSTANCE_PREFERIPADDRESS
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://host.docker.internal:3306/sequence_generator
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: banking-secret
              key: mysql-username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: banking-secret
              key: mysql-password
        - name: MANAGEMENT_METRICS_DISTRIBUTION_PERCENTILESHISTOGRAM_HTTP_SERVER_REQUESTS
          value: 'true'
        - name: OTEL_TRACES_EXPORTER
          value: zipkin
        - name: OTEL_EXPORTER_ZIPKIN_ENDPOINT
          value: http://jaeger-collector.monitoring.svc.cluster.local:9411/api/v2/spans
        - name: OTEL_SERVICE_NAME
          value: sequence-generator
        - name: OTEL_METRICS_EXPORTER
          value: none
        - name: OTEL_LOGS_EXPORTER
          value: none
        - name: OTEL_PROPAGATORS
          value: b3multi,tracecontext
      terminationGracePeriodSeconds: 30
